<?php

namespace Database\Seeders;

use App\Models\Quote;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class QuoteSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Quote::insert([
            ['quote' => "2024", "created_at" => now(), "updated_at" => now()],
            ['quote' => "All you have to be is yourself", "created_at" => now(), "updated_at" => now()],
            ['quote' => "Believe in your flyness...conquer your shyness.", "created_at" => now(), "updated_at" => now()],
            ['quote' => "Burn that excel spread sheet", "created_at" => now(), "updated_at" => now()],
            ['quote' => "Decentralize", "created_at" => now(), "updated_at" => now()],
            ['quote' => "Distraction is the enemy of vision", "created_at" => now(), "updated_at" => now()],
            ['quote' => "Everything you do in life stems from either fear or love", "created_at" => now(), "updated_at" => now()],
            ['quote' => "For me giving up is way harder than trying.", "created_at" => now(), "updated_at" => now()],
            ['quote' => "For me, money is not my definition of success. Inspiring people is a definition of success", "created_at" => now(), "updated_at" => now()],
            ['quote' => "Fur pillows are hard to actually sleep on", "created_at" => now(), "updated_at" => now()],
            ['quote' => "George Bush doesn't care about black people", "created_at" => now(), "updated_at" => now()],
            ['quote' => "Have you ever thought you were in love with someone but then realized you were just staring in a mirror for 20 minutes?", "created_at" => now(), "updated_at" => now()],
            ['quote' => "I care. I care about everything. Sometimes not giving a f#%k is caring the most.", "created_at" => now(), "updated_at" => now()],
            ['quote' => "I feel calm but energized", "created_at" => now(), "updated_at" => now()],
            ['quote' => "I feel like I'm too busy writing history to read it.", "created_at" => now(), "updated_at" => now()],
            ['quote' => "I feel like me and Taylor might still have sex", "created_at" => now(), "updated_at" => now()],
            ['quote' => "I give up drinking every week", "created_at" => now(), "updated_at" => now()],
            ['quote' => "I leave my emojis bart Simpson color", "created_at" => now(), "updated_at" => now()],
            ['quote' => "I love sleep; it's my favorite.", "created_at" => now(), "updated_at" => now()],
            ['quote' => "I make awesome decisions in bike stores!!!", "created_at" => now(), "updated_at" => now()],
            ['quote' => "I really love my Tesla. I'm in the future. Thank you Elon.", "created_at" => now(), "updated_at" => now()],
            ['quote' => "I still think I am the greatest.", "created_at" => now(), "updated_at" => now()],
            ['quote' => "I think I do myself a disservice by comparing myself to Steve Jobs and Walt Disney and human beings that we've seen before. It should be more like Willy Wonka...and welcome to my chocolate factory.", "created_at" => now(), "updated_at" => now()],
            ['quote' => "I want the world to be better! All I want is positive! All I want is dopeness!", "created_at" => now(), "updated_at" => now()],
            ['quote' => "I wish I had a friend like me", "created_at" => now(), "updated_at" => now()],
            ['quote' => "I'd like to meet with Tim Cook. I got some ideas", "created_at" => now(), "updated_at" => now()],
            ['quote' => "I'll say things that are serious and put them in a joke form so people can enjoy them. We laugh to keep from crying.", "created_at" => now(), "updated_at" => now()],
            ['quote' => "I'm a creative genius", "created_at" => now(), "updated_at" => now()],
            ['quote' => "I'm nice at ping pong", "created_at" => now(), "updated_at" => now()],
            ['quote' => "I'm the best", "created_at" => now(), "updated_at" => now()],
            ['quote' => "If I don't scream, if I don't say something then no one's going to say anything.", "created_at" => now(), "updated_at" => now()],
            ['quote' => "If I got any cooler I would freeze to death", "created_at" => now(), "updated_at" => now()],
            ['quote' => "If you have the opportunity to play this game of life you need to appreciate every moment. a lot of people don't appreciate the moment until it's passed.", "created_at" => now(), "updated_at" => now()],
            ['quote' => "Just stop lying about shit. Just stop lying.", "created_at" => now(), "updated_at" => now()],
            ['quote' => "Keep squares out yo circle", "created_at" => now(), "updated_at" => now()],
            ['quote' => "Keep your nose out the sky, keep your heart to god, and keep your face to the rising sun.", "created_at" => now(), "updated_at" => now()],
            ['quote' => "Let's be like water", "created_at" => now(), "updated_at" => now()],
            ['quote' => "Man... whatever happened to my antique fish tank?", "created_at" => now(), "updated_at" => now()],
            ['quote' => "My dad got me a drone for Christmas", "created_at" => now(), "updated_at" => now()],
            ['quote' => "My greatest award is what I'm about to do.", "created_at" => now(), "updated_at" => now()],
            ['quote' => "My greatest pain in life is that I will never be able to see myself perform live.", "created_at" => now(), "updated_at" => now()],
            ['quote' => "One day I'm gon' marry a porn star", "created_at" => now(), "updated_at" => now()],
            ['quote' => "One of my favorite of many things about what the Trump hat represents to me is that people can't tell me what to do because I'm black", "created_at" => now(), "updated_at" => now()],
            ['quote' => "Only free thinkers", "created_at" => now(), "updated_at" => now()],
            ['quote' => "People always say that you can't please everybody. I think that's a cop-out. Why not attempt it? Cause think of all the people that you will please if you try.", "created_at" => now(), "updated_at" => now()],
            ['quote' => "People always tell you 'Be humble. Be humble.' When was the last time someone told you to be amazing? Be great! Be awesome! Be awesome!", "created_at" => now(), "updated_at" => now()],
            ['quote' => "People only get jealous when they care.", "created_at" => now(), "updated_at" => now()],
            ['quote' => "Perhaps I should have been more like water today", "created_at" => now(), "updated_at" => now()],
            ['quote' => "Pulling up in the may bike", "created_at" => now(), "updated_at" => now()],
            ['quote' => "Shut the fuck up I will fucking laser you with alien fucking eyes and explode your fucking head", "created_at" => now(), "updated_at" => now()],
            ['quote' => "Sometimes I push the door close button on people running towards the elevator. I just need my own elevator sometimes. My sanctuary.", "created_at" => now(), "updated_at" => now()],
            ['quote' => "Sometimes you have to get rid of everything", "created_at" => now(), "updated_at" => now()],
            ['quote' => "Style is genderless", "created_at" => now(), "updated_at" => now()],
            ['quote' => "The thought police want to suppress freedom of thought", "created_at" => now(), "updated_at" => now()],
            ['quote' => "The world is our family", "created_at" => now(), "updated_at" => now()],
            ['quote' => "The world is our office", "created_at" => now(), "updated_at" => now()],
            ['quote' => "Today is the best day ever and tomorrow's going to be even better", "created_at" => now(), "updated_at" => now()],
            ['quote' => "Truth is my goal. Controversy is my gym. I'll do a hundred reps of controversy for a 6 pack of truth", "created_at" => now(), "updated_at" => now()],
            ['quote' => "Tweeting is legal and also therapeutic", "created_at" => now(), "updated_at" => now()],
            ['quote' => "We all self-conscious. I'm just the first to admit it.", "created_at" => now(), "updated_at" => now()],
            ['quote' => "We came into a broken world. And we're the cleanup crew.", "created_at" => now(), "updated_at" => now()],
            ['quote' => "You can't look at a glass half full or empty if it's overflowing.", "created_at" => now(), "updated_at" => now()],
            ['quote' => "I hate when I'm on a flight and I wake up with a water bottle next to me like oh great now I gotta be responsible for this water bottle", "created_at" => now(), "updated_at" => now()],
            ['quote' => "All the musicians will be free", "created_at" => now(), "updated_at" => now()],
            ['quote' => "Artists are founders", "created_at" => now(), "updated_at" => now()],
            ['quote' => "Buy property", "created_at" => now(), "updated_at" => now()],
            ['quote' => "Culture is the most powerful force in humanity under God", "created_at" => now(), "updated_at" => now()],
            ['quote' => "Empathy is the glue", "created_at" => now(), "updated_at" => now()],
            ['quote' => "I am one of the most famous people on the planet", "created_at" => now(), "updated_at" => now()],
            ['quote' => "I am running for President of the United States", "created_at" => now(), "updated_at" => now()],
            ['quote' => "I am the head of Adidas. I will bring Adidas and Puma back together and bring me and jay back together", "created_at" => now(), "updated_at" => now()],
            ['quote' => "I am Warhol. I am the No. 1 most impactful artist of our generation. I am Shakespeare in the flesh.", "created_at" => now(), "updated_at" => now()],
            ['quote' => "I channel Will Ferrell when I'm at the daddy daughter dances", "created_at" => now(), "updated_at" => now()],
            ['quote' => "I don't wanna see no woke tweets or hear no woke raps ... it's show time ... it's a whole different energy right now", "created_at" => now(), "updated_at" => now()],
            ['quote' => "I hear people say this person is cool and this person is not cool. People are cool. Man has never invented anything as awesome as a an actual person but sometimes we value the objects we create over life itself", "created_at" => now(), "updated_at" => now()],
            ['quote' => "I honestly need all my Royeres to be museum quality... if I see a fake Royere Ima have to Rick James your couch", "created_at" => now(), "updated_at" => now()],
            ['quote' => "I love UZI. I be saying the same thing about Steve Jobs. I be feeling just like UZI", "created_at" => now(), "updated_at" => now()],
            ['quote' => "I need an army of angels to cover me while I pull this sword out of the stone", "created_at" => now(), "updated_at" => now()],
            ['quote' => "I spoke to Dave Chapelle for two hours this morning. He is our modern day Socrates", "created_at" => now(), "updated_at" => now()],
            ['quote' => "I was just speaking with someone that told me their life story and they used to be homeless.", "created_at" => now(), "updated_at" => now()],
            ['quote' => "I watch Bladerunner on repeat", "created_at" => now(), "updated_at" => now()],
            ['quote' => "I'm giving all Good music artists back the 50% share I have of their masters", "created_at" => now(), "updated_at" => now()],
            ['quote' => "I'm going to personally see to it that Taylor Swift gets her masters back. Scooter is a close family friend", "created_at" => now(), "updated_at" => now()],
            ['quote' => "I'm the new Moses", "created_at" => now(), "updated_at" => now()],
            ['quote' => "Life is the ultimate gift", "created_at" => now(), "updated_at" => now()],
            ['quote' => "Ma\$e is one of my favorite rappers and I based a lot of my flows off of him", "created_at" => now(), "updated_at" => now()],
            ['quote' => "Manga all day", "created_at" => now(), "updated_at" => now()],
            ['quote' => "My first pillar when I'm on the board of adidas will be an adidas Nike collaboration to support community growth", "created_at" => now(), "updated_at" => now()],
            ['quote' => "My mama was a' English teacher. I know how to use correct English but sometimes I just don't feel like it aaaand I ain't got to", "created_at" => now(), "updated_at" => now()],
            ['quote' => "My memories are from the future", "created_at" => now(), "updated_at" => now()],
            ['quote' => "My mother in law Kris Jenner ... makes the best music playlist", "created_at" => now(), "updated_at" => now()],
            ['quote' => "People say it's enough and I got my point across ... the point isn't across until we cross the point", "created_at" => now(), "updated_at" => now()],
            ['quote' => "People tried to talk me out of running for President. Never let weak controlling people kill your spirit", "created_at" => now(), "updated_at" => now()],
            ['quote' => "So many of us need so much less than we have especially when so many of us are in need", "created_at" => now(), "updated_at" => now()],
            ['quote' => "Speak God's truth to power", "created_at" => now(), "updated_at" => now()],
            ['quote' => "The media tries to kill our heroes one at a time", "created_at" => now(), "updated_at" => now()],
            ['quote' => "The world needs more Joy... this idea is super fresh", "created_at" => now(), "updated_at" => now()],
            ['quote' => "There are 5 main pillars in a professional musicians business - Recording, Publishing, Touring, Merchandise & Name and likeness", "created_at" => now(), "updated_at" => now()],
            ['quote' => "There are people sleeping in parking lots", "created_at" => now(), "updated_at" => now()],
            ['quote' => "There's a crying need for civility across the board. We need to and will come together in the name of Jesus.", "created_at" => now(), "updated_at" => now()],
            ['quote' => "There's so many lonely emojis man", "created_at" => now(), "updated_at" => now()],
            ['quote' => "Trust me ... I won't stop", "created_at" => now(), "updated_at" => now()],
            ['quote' => "Two years ago we had 50 million people subscribed to music streaming services around the world. Today we have 400 million.", "created_at" => now(), "updated_at" => now()],
            ['quote' => "We are here to complete the revolution. We are building the future", "created_at" => now(), "updated_at" => now()],
            ['quote' => "We as a people will heal. We will insure the well being of each other", "created_at" => now(), "updated_at" => now()],
            ['quote' => "We have to evolve", "created_at" => now(), "updated_at" => now()],
            ['quote' => "We must and will cure homelessness and hunger. We have the capability as a species", "created_at" => now(), "updated_at" => now()],
            ['quote' => "We must form a union. We must unify", "created_at" => now(), "updated_at" => now()],
            ['quote' => "We used to diss Michael Jackson the media made us call him crazy ... then they killed him", "created_at" => now(), "updated_at" => now()],
            ['quote' => "We will be recognized", "created_at" => now(), "updated_at" => now()],
            ['quote' => "We will change the paradigm", "created_at" => now(), "updated_at" => now()],
            ['quote' => "We will cure hunger", "created_at" => now(), "updated_at" => now()],
            ['quote' => "We will heal. We will cure.", "created_at" => now(), "updated_at" => now()],
            ['quote' => "We're going to move the entire music industry into the 21st Century", "created_at" => now(), "updated_at" => now()],
            ['quote' => "We've gotten comfortable with not having what we deserve", "created_at" => now(), "updated_at" => now()],
            ['quote' => "Who made up the term major label in the first place???", "created_at" => now(), "updated_at" => now()],
            ['quote' => "Winning is the only option", "created_at" => now(), "updated_at" => now()],
            ['quote' => "For me to say I wasn't a genius I'd just be lying to you and to myself", "created_at" => now(), "updated_at" => now()],
            ['quote' => "I've known my mom since I was zero years old. She is quite dope.", "created_at" => now(), "updated_at" => now()],
            ['quote' => "I don't expect to be understood at all.", "created_at" => now(), "updated_at" => now()],
            ['quote' => "I'm on the pursuit of awesomeness, excellence is the bare minimum.", "created_at" => now(), "updated_at" => now()],
            ['quote' => "You basically can say anything to someone on an email or text as long as you put LOL at the end.", "created_at" => now(), "updated_at" => now()],
        ]);
    }
}
